spring:
  application:
    name: weixin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myhome?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
mybatis:
  type-aliases-package: com.home.mapper.*
server:
  port: 8082
  servlet:
    context-path:

  # redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3
#  password:
  pool:
    minIdle: 1
    maxIdle: 10
    maxWait: 3
    maxActive: 8
thymeleaf:
  cache: false
  prefix: classpath:templates/
  suffix: .html
  encoding: UTF-8
  content-type: text/html
  mode: HTML5
